theme = 'diary'
baseURL = 'https://love.makotokukuu.xyz/'
title = "誠のブログ"
languageCode = 'zh-cn'
DefaultContentLanguage = "zh"

[params]
	subtitle = "Makoto's Blog."
	enableGitalk = false
	enableGiscus = false
	enableOpenGraph = true
	enableTwitterCards = true
	description = "Makoto's Blog."

[taxonomies]
	tag = "tags"
	category = "categories"

[[menu.main]]
	url = "/posts"
	name = "归档"
	weight = 1
[[menu.main]]
	url = "/categories"
	name = "分类"
	weight = 2
[[menu.main]]
	url = "/tags"
	name = "标签"
	weight = 3
[[menu.main]]
	url = "/index.xml"
	name = "RSS"
	weight = 4

